openapi: "3.0.3"

info:
  title: "react_vite_sample login API"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "local server"

paths:
  "/login":
    get:
      summary: "Get Login Info"
      description: "Check you are already login state"
      tags: ["login"]
      responses:
        "200":
          description: "Success operation"
          content:
            application/json:
              schema:
                type: string
                example: false
    post:
      summary: "Post Login Info"
      description: "Post login state info"
      tags: ["login"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "Success operation"
          content:
            application/json:
              schema:
                type: string
                example: true

tags:
  - name: "login"
    description: "Concerned about login"
