openapi: "3.0.3"

info:
  title: "react_vite_sample login API"
  version: "1.0.0"

servers:
  - url: "http://localhost:5000"
    description: "local server"

paths:
  "/login":
    get:
      summary: "Get Login Info"
      description: "Check you are already login state"
      tags: ["login"]
      responses:
        "200":
          description: "Success operation"
          content:
            application/json:
              schema:
                type: string
                example: false

tags:
  - name: "login"
    description: "Concerned about login"
