openapi: 3.0.3
info:
  title: react_vite_sample API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local server
tags:
  - name: login
    description: Concerned about login
  - name: form
    description: Concerned about form
  - name: customer
    description: Concerned about customer
paths:
  /login:
    get:
      tags:
        - login
      summary: Get Login Info
      description: Check you are already login state
      operationId: loginGET
      responses:
        "200":
          description: Success operation
          content:
            application/json:
              schema:
                type: string
                example: "false"
                x-content-type: application/json
      x-swagger-router-controller: Login
    post:
      tags:
        - login
      summary: Post Login Info
      description: Post login state info
      operationId: loginPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/login_body"
        required: true
      responses:
        "200":
          description: Success operation
          content:
            application/json:
              schema:
                type: string
                example: "true"
                x-content-type: application/json
      x-swagger-router-controller: Login
  /form:
    post:
      tags:
        - form
      summary: Post Form Info
      description: Post form and return state info
      operationId: formPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/form_body"
        required: true
      responses:
        "200":
          description: Success operation
          content:
            application/json:
              schema:
                type: string
                example: "true"
                x-content-type: application/json
      x-swagger-router-controller: Form
  /customer:
    get:
      tags:
        - customer
      summary: Get Customer Info
      description: Get your customer list
      operationId: customerGET
      responses:
        "200":
          description: Success operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/customerList"
              x-content-type: application/json
      x-swagger-router-controller: Customer
  /customer/{id}:
    get:
      tags:
        - customer
      summary: Get a customer detail by ID
      operationId: customerIdGET
      parameters:
        - name: id
          in: path
          description: Numeric ID of the user to get
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        "200":
          description: Success operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/customerDetail"
              x-content-type: application/json
      x-swagger-router-controller: Customer
components:
  schemas:
    login_body:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    form_body:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        city:
          type: string
        option:
          type: string
    customerList:
      type: array
      items:
        $ref: "#/components/schemas/customerList_inner"
    customerDetail:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: nyaomaru
        city:
          type: string
          example: forest 1
        favorite:
          type: string
          example: catnip
      example:
        city: forest 1
        name: nyaomaru
        id: id
        favorite: catnip
    customerList_inner:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      example:
        - id: 1
          name: nyaomaru
        - id: 2
          name: cat
        - id: 3
          name: dog
